_BASE_: "./Base-RCNN-FPN.yaml"
MODEL:
  MASK_ON: True
  # TEXTFUSENET_MUTIL_PATH_FUSE_ON: True
  WEIGHTS: "./out_dir_r101/icdar2013_model/model_ic13_r101.pth"
  PIXEL_STD: [57.375, 57.120, 58.395]
  RESNETS:
    STRIDE_IN_1X1: False  # this is a C2 model
    NUM_GROUPS: 32
    WIDTH_PER_GROUP: 8
    DEPTH: 101
  ROI_HEADS:
    NMS_THRESH_TEST: 0.3
  # TEXTFUSENET_SEG_HEAD:
  #   FPN_FEATURES_FUSED_LEVEL: 2
  #   POOLER_SCALES: (0.0625,)
  DEVICE: 'cuda'

DATASETS:
  TRAIN: ("icdar2013",)
  TEST: ("icdar2013",)
SOLVER:
  IMS_PER_BATCH: 4
  BASE_LR: 0.001
  STEPS: (40000,80000,)
  MAX_ITER: 120000
  CHECKPOINT_PERIOD: 2500

INPUT:
  MIN_SIZE_TRAIN: (800,1000,1200)
  MAX_SIZE_TRAIN: 1500
  MIN_SIZE_TEST: 800
  MAX_SIZE_TEST: 1500
  

OUTPUT_DIR: "./out_dir_r101/icdar2013_model/"
